/*

 _____   ____         ______ ____
/__  /  / __ \ _  __ / ____// __ \
  / /  / / / /| |/_//___ \ / / / /
 / /__/ /_/ /_>  < ____/ // /_/ /
/____/\____//_/|_|/_____/ \____/

Zilog 80 Emulator

Basic interface to the Z80 processor and associated modules.
Can be run as a Sinclair ZX Spectrum or used as a basis for a larger project.

Z80Instructions.c : Instructions that the Z80 CPU can perform

*/

#include "Z80Instructions.h"

const char* instructions_IYBitInstructionText[0x100] = {
    "null"
};

const char* instructions_IYInstructionText[0x100] = {
    "null"
};

const char* instructions_IXInstructionText[0x100] = {
    [0x09] = "ADD IX,BC",
    [0x19] = "ADD IX,DE",
    [0x21] = "LD IX,NN",
    [0x22] = "LD (NN),IX",
    [0x23] = "INC IX",
    [0x24] = "INC IXH",
    [0x25] = "DEC IXH",
    [0x26] = "LD IXH,N",
    [0x29] = "ADD IX,IX",
    [0x2A] = "LD IX,(NN)",
    [0x2B] = "DEC IX",
    [0x2C] = "INC IXL",
    [0x2D] = "DEC IXL",
    [0x2E] = "LD IXL,N",
    [0x34] = "INC (IX+N)",
    [0x35] = "DEC (IX+N)",
    [0x36] = "LD (IX+N),N",
    [0x39] = "ADD IX,SP",
    [0x44] = "LD B,IXH",
    [0x45] = "LD B,IXL",
    [0x46] = "LD B,(IX+N)",
    [0x4C] = "LD C,IXH",
    [0x4D] = "LD C,IXL",
    [0x4E] = "LD C,(IX+N)",
    [0x54] = "LD D,IXH",
    [0x55] = "LD D,IXL",
    [0x56] = "LD D,(IX+N)",
    [0x5C] = "LD E,IXH",
    [0x5D] = "LD E,IXL",
    [0x5E] = "LD E,(IX+N)",
    [0x60] = "LD IXH,B",
    [0x61] = "LD IXH,C",
    [0x62] = "LD IXH,D",
    [0x63] = "LD IXH,E",
    [0x64] = "LD IXH,IXH",
    [0x65] = "LD IXH,IXL",
    [0x66] = "LD H,(IX+N)",
    [0x67] = "LD IXH,A",
    [0x68] = "LD IXL,B",
    [0x69] = "LD IXL,C",
    [0x6A] = "LD IXL,D",
    [0x6B] = "LD IXL,E",
    [0x6C] = "LD IXL,IXH",
    [0x6D] = "LD IXL,IXL",
    [0x6E] = "LD L,(IX+N)",
    [0x6F] = "LD IXL,A",
    [0x70] = "LD (IX+N),B",
    [0x71] = "LD (IX+N),C",
    [0x72] = "LD (IX+N),D",
    [0x73] = "LD (IX+N),E",
    [0x74] = "LD (IX+N),H",
    [0x75] = "LD (IX+N),L",
    [0x77] = "LD (IX+N),A",
    [0x7C] = "LD A,IXH",
    [0x7D] = "LD A,IXL",
    [0x7E] = "LD A,(IX+N)",
    [0x84] = "ADD A,IXH",
    [0x85] = "ADD A,IXL",
    [0x86] = "ADD A,(IX+N)",
    [0x8C] = "ADC A,IXH",
    [0x8D] = "ADC A,IXL",
    [0x8E] = "ADC A,(IX+N)",
    [0x94] = "SUB A,IXH",
    [0x95] = "SUB A,IXL",
    [0x96] = "SUB A,(IX+N)",
    [0x9C] = "SBC A,IXH",
    [0x9D] = "SBC A,IXL",
    [0x9E] = "SBC A,(IX+N)",
    [0xA4] = "AND A,IXH",
    [0xA5] = "AND A,IXL",
    [0xA6] = "AND A,(IX+N)",
    [0xAC] = "XOR A,IXH",
    [0xAD] = "XOR A,IXL",
    [0xAE] = "XOR A,(IX+N)",
    [0xB4] = "OR A,IXH",
    [0xB5] = "OR A,IXL",
    [0xB6] = "OR A,(IX+N)",
    [0xBC] = "CP A,IXH",
    [0xBD] = "CP A,IXL",
    [0xBE] = "CP A,(IX+N)",
    [0xCB] = "IX BITS PREFIX",
    [0xE1] = "POP IX",
    [0xE3] = "EX (SP),IX",
    [0xE5] = "PUSH IX",
    [0xE9] = "JP (IX)",
    [0xF9] = "LD SP,IX"
};

const char* instructions_bitInstructionText[0x100] = {
    "RLC B",
    "RLC C",
    "RLC D",
    "RLC E",
    "RLC H",
    "RLC L",
    "RLC (HL)",
    "RLC A",
    "RRC B",
    "RRC C",
    "RRC D",
    "RRC E",
    "RRC H",
    "RRC L",
    "RRC (HL)",
    "RRC A",
    "RL B",
    "RL C",
    "RL D",
    "RL E",
    "RL H",
    "RL L",
    "RL (HL)",
    "RL A",
    "RR B",
    "RR C",
    "RR D",
    "RR E",
    "RR H",
    "RR L",
    "RR (HL)",
    "RR A",
    "SLA B",
    "SLA C",
    "SLA D",
    "SLA E",
    "SLA H",
    "SLA L",
    "SLA (HL)",
    "SLA A",
    "SRA B",
    "SRA C",
    "SRA D",
    "SRA E",
    "SRA H",
    "SRA L",
    "SRA (HL)",
    "SRA A",
    "SLL B",
    "SLL C",
    "SLL D",
    "SLL E",
    "SLL H",
    "SLL L",
    "SLL (HL)",
    "SLL A",
    "SRL B",
    "SRL C",
    "SRL D",
    "SRL E",
    "SRL H",
    "SRL L",
    "SRL (HL)",
    "SRL A",
    "BIT 0,B",
    "BIT 0,C",
    "BIT 0,D",
    "BIT 0,E",
    "BIT 0,H",
    "BIT 0,L",
    "BIT 0,(HL)",
    "BIT 0,A",
    "BIT 1,B",
    "BIT 1,C",
    "BIT 1,D",
    "BIT 1,E",
    "BIT 1,H",
    "BIT 1,L",
    "BIT 1,(HL)",
    "BIT 1,A",
    "BIT 2,B",
    "BIT 2,C",
    "BIT 2,D",
    "BIT 2,E",
    "BIT 2,H",
    "BIT 2,L",
    "BIT 2,(HL)",
    "BIT 2,A",
    "BIT 3,B",
    "BIT 3,C",
    "BIT 3,D",
    "BIT 3,E",
    "BIT 3,H",
    "BIT 3,L",
    "BIT 3,(HL)",
    "BIT 3,A",
    "BIT 4,B",
    "BIT 4,C",
    "BIT 4,D",
    "BIT 4,E",
    "BIT 4,H",
    "BIT 4,L",
    "BIT 4,(HL)",
    "BIT 4,A",
    "BIT 5,B",
    "BIT 5,C",
    "BIT 5,D",
    "BIT 5,E",
    "BIT 5,H",
    "BIT 5,L",
    "BIT 5,(HL)",
    "BIT 5,A",
    "BIT 6,B",
    "BIT 6,C",
    "BIT 6,D",
    "BIT 6,E",
    "BIT 6,H",
    "BIT 6,L",
    "BIT 6,(HL)",
    "BIT 6,A",
    "BIT 7,B",
    "BIT 7,C",
    "BIT 7,D",
    "BIT 7,E",
    "BIT 7,H",
    "BIT 7,L",
    "BIT 7,(HL)",
    "BIT 7,A",
    "RES 0,B",
    "RES 0,C",
    "RES 0,D",
    "RES 0,E",
    "RES 0,H",
    "RES 0,L",
    "RES 0,(HL)",
    "RES 0,A",
    "RES 1,B",
    "RES 1,C",
    "RES 1,D",
    "RES 1,E",
    "RES 1,H",
    "RES 1,L",
    "RES 1,(HL)",
    "RES 1,A",
    "RES 2,B",
    "RES 2,C",
    "RES 2,D",
    "RES 2,E",
    "RES 2,H",
    "RES 2,L",
    "RES 2,(HL)",
    "RES 2,A",
    "RES 3,B",
    "RES 3,C",
    "RES 3,D",
    "RES 3,E",
    "RES 3,H",
    "RES 3,L",
    "RES 3,(HL)",
    "RES 3,A",
    "RES 4,B",
    "RES 4,C",
    "RES 4,D",
    "RES 4,E",
    "RES 4,H",
    "RES 4,L",
    "RES 4,(HL)",
    "RES 4,A",
    "RES 5,B",
    "RES 5,C",
    "RES 5,D",
    "RES 5,E",
    "RES 5,H",
    "RES 5,L",
    "RES 5,(HL)",
    "RES 5,A",
    "RES 6,B",
    "RES 6,C",
    "RES 6,D",
    "RES 6,E",
    "RES 6,H",
    "RES 6,L",
    "RES 6,(HL)",
    "RES 6,A",
    "RES 7,B",
    "RES 7,C",
    "RES 7,D",
    "RES 7,E",
    "RES 7,H",
    "RES 7,L",
    "RES 7,(HL)",
    "RES 7,A",
    "SET 0,B",
    "SET 0,C",
    "SET 0,D",
    "SET 0,E",
    "SET 0,H",
    "SET 0,L",
    "SET 0,(HL)",
    "SET 0,A",
    "SET 1,B",
    "SET 1,C",
    "SET 1,D",
    "SET 1,E",
    "SET 1,H",
    "SET 1,L",
    "SET 1,(HL)",
    "SET 1,A",
    "SET 2,B",
    "SET 2,C",
    "SET 2,D",
    "SET 2,E",
    "SET 2,H",
    "SET 2,L",
    "SET 2,(HL)",
    "SET 2,A",
    "SET 3,B",
    "SET 3,C",
    "SET 3,D",
    "SET 3,E",
    "SET 3,H",
    "SET 3,L",
    "SET 3,(HL)",
    "SET 3,A",
    "SET 4,B",
    "SET 4,C",
    "SET 4,D",
    "SET 4,E",
    "SET 4,H",
    "SET 4,L",
    "SET 4,(HL)",
    "SET 4,A",
    "SET 5,B",
    "SET 5,C",
    "SET 5,D",
    "SET 5,E",
    "SET 5,H",
    "SET 5,L",
    "SET 5,(HL)",
    "SET 5,A",
    "SET 6,B",
    "SET 6,C",
    "SET 6,D",
    "SET 6,E",
    "SET 6,H",
    "SET 6,L",
    "SET 6,(HL)",
    "SET 6,A",
    "SET 7,B",
    "SET 7,C",
    "SET 7,D",
    "SET 7,E",
    "SET 7,H",
    "SET 7,L",
    "SET 7,(HL)",
    "SET 7,A",
};

const char* instructions_extendedInstructionText[0x100] = {
    [0x40] = "IN B,(C)",
    [0x41] = "OUT (C),B",
    [0x42] = "SBC HL,BC",
    [0x43] = "LD (NN),BC",
    [0x44] = "NEG",
    [0x45] = "RETN",
    [0x46] = "IM 0",
    [0x47] = "LD I,A",
    [0x48] = "IN C,(C)",
    [0x49] = "OUT (C),C",
    [0x4A] = "ADC HL,BC",
    [0x4B] = "LD BC,(NN)",
    [0x4D] = "RETI",
    [0x4F] = "LD R,A",
    [0x50] = "IN D,(C)",
    [0x51] = "OUT (C),D",
    [0x52] = "SBC HL,DE",
    [0x53] = "LD (NN),DE",
    [0x55] = "RETN",
    [0x56] = "IM 1",
    [0x57] = "LD A,I",
    [0x58] = "IN E,(C)",
    [0x59] = "OUT (C),E",
    [0x5A] = "ADC HL,DE",
    [0x5B] = "LD DE,(NN)",
    [0x5D] = "RETN",
    [0x5E] = "IM 2",
    [0x5F] = "LD A,R",
    [0x60] = "IN H,(C)",
    [0x61] = "OUT (C),H",
    [0x62] = "SBC HL,HL",
    [0x65] = "RETN",
    [0x66] = "IM 0",
    [0x67] = "RRD",
    [0x68] = "IN L,(C)",
    [0x69] = "OUT (C),L",
    [0x6A] = "ADC HL,HL",
    [0x6D] = "RETN",
    [0x6F] = "RLD",
    [0x72] = "SBC HL,SP",
    [0x73] = "LD (NN),SP",
    [0x75] = "RETN",
    [0x76] = "IM 1",
    [0x78] = "IN A,(C)",
    [0x79] = "OUT (C),A",
    [0x7A] = "ADC HL,SP",
    [0x7B] = "LD SP,(NN)",
    [0x7D] = "RETN",
    [0x7E] = "IM 2",
    [0xA0] = "LDI",
    [0xA1] = "CPI",
    [0xA2] = "INI",
    [0xA3] = "OUTI",
    [0xA8] = "LDD",
    [0xA9] = "CPD",
    [0xAA] = "IND",
    [0xAB] = "OUTD",
    [0xB0] = "LDIR",
    [0xB1] = "CPIR",
    [0xB2] = "INIR",
    [0xB3] = "OTIR",
    [0xB8] = "LDDR",
    [0xB9] = "CPDR",
    [0xBA] = "INDR",
    [0xBB] = "OTDR"
};

const char* instructions_mainInstructionText[0x100] = {
    "NOP",
    "LD BC,NN",
    "LD (BC),A",
    "INC BC",
    "INC B",
    "DEC B",
    "LD B,N",
    "RCLA",
    "EX AF,AF'",
    "ADD HL,BC",
    "LD A,(BC)",
    "DEC BC",
    "INC C",
    "DEC C",
    "LD C,N",
    "RRCA",
    "DJNZ N",
    "LD DE,NN",
    "LD (DE),A",
    "INC DE",
    "INC D",
    "DEC D",
    "LD D,N",
    "RLA",
    "JR N",
    "ADD HL,DE",
    "LD A,(DE)",
    "DEC DE",
    "INC E",
    "DEC E",
    "LD E,N",
    "RRA",
    "JR NZ,N",
    "LD HL,NN",
    "LD (NN),HL",
    "INC HL",
    "INC H",
    "DEC H",
    "LD H,N",
    "DAA",
    "JR Z,N",
    "ADD HL,HL",
    "LD HL,NN",
    "DEC HL",
    "INC L",
    "DEC L",
    "LD L,N",
    "CPL",
    "JR NC,N",
    "LD SP,NN",
    "LD (NN),A",
    "INC SP",
    "INC (HL)",
    "DEC (HL)",
    "LD (HL),N",
    "SCF",
    "JR C,N",
    "ADD HL,SP",
    "LD A,(NN)",
    "DEC SP",
    "INC A",
    "DEC A",
    "LD A,N",
    "CCF",
    "LD B,B",
    "LD B,C",
    "LD B,D",
    "LD B,E",
    "LD B,H",
    "LD B,L",
    "LD B,(HL)",
    "LD B,A",
    "LD C,B",
    "LD C,C",
    "LD C,D",
    "LD C,E",
    "LD C,H",
    "LD C,L",
    "LD C,(HL)",
    "LD C,A",
    "LD D,B",
    "LD D,C",
    "LD D,D",
    "LD D,E",
    "LD D,H",
    "LD D,L",
    "LD D,(HL)",
    "LD D,A",
    "LD E,B",
    "LD E,C",
    "LD E,D",
    "LD E,E",
    "LD E,H",
    "LD E,L",
    "LD E,(HL)",
    "LD E,A",
    "LD H,B",
    "LD H,C",
    "LD H,D",
    "LD H,E",
    "LD H,H",
    "LD H,L",
    "LD H,(HL)",
    "LD H,A",
    "LD L,B",
    "LD L,C",
    "LD L,D",
    "LD L,E",
    "LD L,H",
    "LD L,L",
    "LD L,(HL)",
    "LD L,A",
    "LD (HL),B",
    "LD (HL),C",
    "LD (HL),D",
    "LD (HL),E",
    "LD (HL),H",
    "LD (HL),L",
    "HALT",
    "LD (HL),A",
    "LD A,B",
    "LD A,C",
    "LD A,D",
    "LD A,E",
    "LD A,H",
    "LD A,L",
    "LD A,(HL)",
    "LD A,A",
    "ADD A,B",
    "ADD A,C",
    "ADD A,D",
    "ADD A,E",
    "ADD A,H",
    "ADD A,L",
    "ADD A,(HL)",
    "ADD A,A",
    "ADC A,B",
    "ADC A,C",
    "ADC A,D",
    "ADC A,E",
    "ADC A,H",
    "ADC A,L",
    "ADC A,(HL)",
    "ADC A,A",
    "SUB A,B",
    "SUB A,C",
    "SUB A,D",
    "SUB A,E",
    "SUB A,H",
    "SUB A,L",
    "SUB A,(HL)",
    "SUB A,A",
    "SBC A,B",
    "SBC A,C",
    "SBC A,D",
    "SBC A,E",
    "SBC A,H",
    "SBC A,L",
    "SBC A,(HL)",
    "SBC A,A",
    "AND A,B",
    "AND A,C",
    "AND A,D",
    "AND A,E",
    "AND A,H",
    "AND A,L",
    "AND A,(HL)",
    "AND A,A",
    "XOR A,B",
    "XOR A,C",
    "XOR A,D",
    "XOR A,E",
    "XOR A,H",
    "XOR A,L",
    "XOR A,(HL)",
    "XOR A,A",
    "OR A,B",
    "OR A,C",
    "OR A,D",
    "OR A,E",
    "OR A,H",
    "OR A,L",
    "OR A,(HL)",
    "OR A,A",
    "CP A,B",
    "CP A,C",
    "CP A,D",
    "CP A,E",
    "CP A,H",
    "CP A,L",
    "CP A,(HL)",
    "CP A,A",
    "RET NZ",
    "POP BC",
    "JP NZ,NN",
    "JP NN",
    "CALL NZ,NN",
    "PUSH BC",
    "ADD A,N",
    "RST 00h",
    "RET Z",
    "RET",
    "JP Z,NN",
    "PREFIX BITS",
    "CALL Z,NN",
    "CALL NN",
    "ADC A,N",
    "RST 08h",
    "RET NC",
    "POP DE",
    "JP NC,NN",
    "OUT (N),A",
    "CALL NC,NN",
    "PUSH DE",
    "SUB A,N",
    "RST 10h",
    "RET C",
    "EXX",
    "JP C,NN",
    "IN A,(N)",
    "CALL C,NN",
    "PREFIX IX",
    "SBC A,N",
    "RST 18h",
    "RET PO",
    "POP HL",
    "JP PO,NN",
    "EX (SP),HL",
    "CALL PO,NN",
    "PUSH HL",
    "AND A,N",
    "RST 20h",
    "RET PE",
    "JP (HL)",
    "JP PE,NN",
    "EX DE,HL",
    "CALL PE,NN",
    "PREFIX EXTD",
    "XOR A,N",
    "RST 28h",
    "RET P",
    "POP AF",
    "JP P,NN",
    "DI",
    "CALL P,NN",
    "PUSH AF",
    "OR A,N",
    "RST 30h",
    "RET M",
    "LD SP,HL",
    "JP M,NN",
    "EI",
    "CALL M,NN",
    "PREFIX IY",
    "CP A,N",
    "RST 38h"
};